server:
  error:
    whitelabel:
      enabled: false
  port: ${port:9002}
spring:
  application:
    name: bill-summary
  profiles:
    active: development
security:
  basic:
    enabled: false # turn off securing our application endpoints
management:
  security:
    enabled: false


