apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: billing-service-info-virtual-service
spec:
  hosts:
    - billing-service-info-service
  http:
  - route:
    - destination:
        host: billing-service-info-service
        subset: v3
