apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-service-virtual-service
spec:
  hosts:
  - customer
  http:
  - fault:
      abort:
        percent: 80
        httpStatus: 400
    route:
    - destination:
        host: customer
        subset: v1


